---
- name: Install darkice and alsa-utils
  apt:
    name: darkice
    state: present
    update_cache: true
  loop:
    - alsa-utils
    - darkice
  loop_control:
    loop_var: package

- name: Copy icecast2 configuration file
  copy:
    src: ../files/darkice.cfg
    dest: /etc/darkice/darkice.cfg
    owner: "{{ ansible_user }}"

- name: Copy darkice daemon file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/x20mar/darkice-with-mp3-for-raspberry-pi/master/init.d-darkice
    dest: /etc/init.d/darkice
    mode: a+x
