---
- name: Install darkice and alsa-utils
  apt:
    name: darkice
    state: present
    update_cache: true
  loop:
    - alsa-utils
    - darkice
  loop_control:
    loop_var: package

- name: Copy icecast2 configuration file
  copy:
    src: ../files/darkice.cfg
    dest: /etc/darkice/darkice.cfg
    owner: "{{ ansible_user }}"
    mode: 0644
