---
# tasks file for sonos-streamer
- name: Include initial role tasks
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - prerequisites.yml
    # - check_install.yml

- name: Install service if not already or if force_install is true
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - install_icecast.yml
    - install_darkice.yml
    - configure.yml
  # when: force_install is true or not_installed is true

- name: Make sure services are enabled and running
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - startup.yml

- name: Include verify tasks
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - verify.yml
  when: disable_verification is false
