---
# tasks file for sonos-streamer
- name: Include role tasks
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - prerequisites.yml
    - install_icecast.yml
    - install_darkice.yml
    - configure.yml
    - startup.yml
