---
- name: Launch icecast2
  ansible.builtin.command:
    cmd: icecast2 -c ~/icecast2/icecast.xml -b

# - name: Launch darkice
#   ansible.builtin.command:
#     # cmd: darkice -c ~/darkice/darkice.cfg
#     cmd: sudo darkice -v 10

- name: Launch darkice daemon
  ansible.builtin.command:
    cmd: /etc/init.d/darkice start
  become: true
