---
- name: Launch icecast2
  ansible.builtin.command:
    cmd: icecast2 -c /home/{{ ansible_user }}/icecast2/icecast.xml -b

- name: Launch darkice
  ansible.builtin.command:
    cmd: darkice -c /etc/darkice/darkice.cfg
